=== RaylsonCarlos/CampeonatoBrasileiroWebScraper/XML/CB_v2.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="cb" type="cbType"/>
    
    <xs:complexType name="cbType">
        <xs:sequence>
            <xs:element name="rodada" type="rodadaType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="ano" type="xs:positiveInteger"/>
        <xs:attribute name="serie" type="xs:string"/>
    </xs:complexType>
    
    <xs:complexType name="rodadaType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="jogo" type="jogoType"/>
        </xs:sequence>
        <xs:attribute name="n" type="xs:positiveInteger"/>
    </xs:complexType>
    
    <xs:complexType name="jogoType">
        <xs:sequence>
            <xs:element name="equipe" type="equipeType"/>
            <xs:element name="equipe" type="equipeType"/>
        </xs:sequence>
        <xs:attribute name="horario" type="xs:dateTime"/>
    </xs:complexType>
    
    <xs:complexType name="equipeType">
        <xs:attribute name="tipo">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="mandante"/>
                    <xs:enumeration value="visitante"/>
                </xs:restriction>
            </xs:simpleType>            
        </xs:attribute>
        <xs:attribute name="time" type="xs:string"/>
        <xs:attribute name="gols" type="xs:nonNegativeInteger"/>
    </xs:complexType>

</xs:schema>

=== RaylsonCarlos/CampeonatoBrasileiroWebScraper/XML/CB2018A.xml
<cb ano="2018" serie="A" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CB_v2.xsd"><rodada n="38"><jogo horario="2018-12-01T19:00:00"><equipe gols="1" time="Atlético-MG" tipo="mandante" /><equipe gols="0" time="Botafogo-RJ" tipo="visitante" /></jogo><jogo horario="2018-12-01T19:00:00"><equipe gols="1" time="Flamengo-RJ" tipo="mandante" /><equipe gols="2" time="Atlético-PR" tipo="visitante" /></jogo><jogo horario="2018-12-02T17:00:00"><equipe gols="1" time="Paraná-PR" tipo="mandante" /><equipe gols="1" time="Internacional-RS" tipo="visitante" /></jogo><jogo horario="2018-12-02T17:00:00"><equipe gols="1" time="Chapecoense-SC" tipo="mandante" /><equipe gols="0" time="São Paulo-SP" tipo="visitante" /></jogo><jogo horario="2018-12-02T17:00:00"><equipe gols="0" time="Bahia-BA" tipo="mandante" /><equipe gols="0" time="Cruzeiro-MG" tipo="visitante" /></jogo><jogo horario="2018-12-02T17:00:00"><equipe gols="1" time="Fluminense-RJ" tipo="mandante" /><equipe gols="0" time="América-MG" tipo="visitante" /></jogo><jogo horario="2018-12-02T17:00:00"><equipe gols="0" time="Ceará-CE" tipo="mandante" /><equipe gols="0" time="Vasco da Gama-RJ" tipo="visitante" /></jogo><jogo horario="2018-12-02T17:00:00"><equipe gols="2" time="Sport-PE" tipo="mandante" /><equipe gols="1" time="Santos-SP" tipo="visitante" /></jogo><jogo horario="2018-12-02T17:00:00"><equipe gols="3" time="Palmeiras-SP" tipo="mandante" /><equipe gols="2" time="Vitória-BA" tipo="visitante" /></jogo><jogo horario="2018-12-02T17:00:00"><equipe gols="1" time="Grêmio-RS" tipo="mandante" /><equipe gols="0" time="Corinthians-SP" tipo="visitante" /></jogo></rodada><rodada n="37"><jogo horario="2018-11-24T20:00:00"><equipe gols="3" time="Santos-SP" tipo="mandante" /><equipe gols="2" time="Atlético-MG" tipo="visitante" /></jogo><jogo horario="2018-11-25T17:00:00"><equipe gols="0" time="Cruzeiro-MG" tipo="mandante" /><equipe gols="2" time="Flamengo-RJ" tipo="visitante" /></jogo><jogo horario="2018-11-25T17:00:00"><equipe gols="0" time="Vitória-BA" tipo="mandante" /><equipe gols="0" time="Grêmio-RS" tipo="visitante" /></jogo><jogo horario="2018-11-25T17:00:00"><equipe gols="0" time="Vasco da Gama-RJ" tipo="mandante" /><equipe gols="1" time="Palmeiras-SP" tipo="visitante" /></jogo><jogo horario="2018-11-25T17:00:00"><equipe gols="2" time="Atlético-PR" tipo="mandante" /><equipe gols="2" time="Ceará-CE" tipo="visitante" /></jogo><jogo horario="2018-11-25T19:00:00"><equipe gols="1" time="América-MG" tipo="mandante" /><equipe gols="0" time="Bahia-BA" tipo="visitante" /></jogo><jogo horario="2018-11-25T19:00:00"><equipe gols="0" time="Corinthians-SP" tipo="mandante" /><equipe gols="0" time="Chapecoense-SC" tipo="visitante" /></jogo><jogo horario="2018-11-25T19:00:00"><equipe gols="2" time="Internacional-RS" tipo="mandante" /><equipe gols="0" time="Fluminense-RJ" tipo="visitante" /></jogo><jogo horario="2018-11-26T20:00:00"><equipe gols="0" time="São Paulo-SP" tipo="mandante" /><equipe gols="0" time="Sport-PE" tipo="visitante" /></jogo><jogo horario="2018-11-26T20:00:00"><equipe gols="2" time="Botafogo-RJ" tipo="mandante" /><equipe gols="1" time="Paraná-PR" tipo="visitante" /></jogo></rodada><rodada n="36"><jogo horario="2018-11-21T19:30:00"><equipe gols="1" time="Internacional-RS" tipo="mandante" /><equipe gols="2" time="Atlético-MG" tipo="visitante" /></jogo><jogo horario="2018-11-21T21:00:00"><equipe gols="1" time="Santos-SP" tipo="mandante" /><equipe gols="1" time="Botafogo-RJ" tipo="visitante" /></jogo><jogo horario="2018-11-21T21:45:00"><equipe gols="3" time="Cruzeiro-MG" tipo="mandante" /><equipe gols="0" time="Vitória-BA" tipo="visitante" /></jogo><jogo horario="2018-11-21T21:45:00"><equipe gols="1" time="Atlético-PR" tipo="mandante" /><equipe gols="0" time="Corinthians-SP" tipo="visitante" /></jogo><jogo horario="2018-11-21T21:45:00"><equipe gols="2" time="Flamengo-RJ" tipo="mandante" /><equipe gols="0" time="Grêmio-RS" tipo="visitante" /></jogo><jogo horario="2018-11-21T21:45:00"><equipe gols="4" time="Palmeiras-SP" tipo="mandante" /><equipe gols="0" time="América-MG" tipo="visitante" /></jogo><jogo horario="2018-11-22T20:00:00"><equipe gols="2" time="Vasco da Gama-RJ" tipo="mandante" /><equipe gols="0" time="São Paulo-SP" tipo="visitante" /></jogo><jogo horario="2018-11-22T21:00:00"><equipe gols="1" time="Ceará-CE" tipo="mandante" /><equipe gols="0" time="Paraná-PR" tipo="visitante" /></jogo><jogo horario="2018-11-22T21:00:00"><equipe gols="2" time="Chapecoense-SC" tipo="mandante" /><equipe gols="1" time="Sport-PE" tipo="visitante" /></jogo><jogo horario="2018-11-22T21:00:00"><equipe gols="2" time="Bahia-BA" tipo="mandante" /><equipe gols="0" time="Fluminense-RJ" tipo="visitante" /></jogo></rodada><rodada n="35"><jogo horario="2018-11-17T19:00:00"><equipe gols="1" time="Vitória-BA" tipo="mandante" /><equipe gols="2" time="Atlético-PR" tipo="visitante" /></jogo><jogo horario="2018-11-17T19:00:00"><equipe gols="1" time="Corinthians-SP" tipo="mandante" /><equipe gols="0" time="Vasco da Gama-RJ" tipo="visitante" /></jogo><jogo horario="2018-11-17T21:00:00"><equipe gols="1" time="Atlético-MG" tipo="mandante" /><equipe gols="0" time="Bahia-BA" tipo="visitante" /></jogo><jogo horario="2018-11-18T17:00:00"><equipe gols="1" time="Botafogo-RJ" tipo="mandante" /><equipe gols="0" time="Internacional-RS" tipo="visitante" /></jogo><jogo horario="2018-11-18T17:00:00"><equipe gols="0" time="Sport-PE" tipo="mandante" /><equipe gols="1" time="Flamengo-RJ" tipo="visitante" /></jogo><jogo horario="2018-11-18T17:00:00"><equipe gols="2" time="América-MG" tipo="mandante" /><equipe gols="1" time="Santos-SP" tipo="visitante" /></jogo><jogo horario="2018-11-18T17:00:00"><equipe gols="1" time="Paraná-PR" tipo="mandante" /><equipe gols="1" time="Palmeiras-SP" tipo="visitante" /></jogo><jogo horario="2018-11-18T19:00:00"><equipe gols="2" time="Grêmio-RS" tipo="mandante" /><equipe gols="0" time="Chapecoense-SC" tipo="visitante" /></jogo><jogo horario="2018-11-18T19:00:00"><equipe gols="1" time="São Paulo-SP" tipo="mandante" /><equipe gols="0" time="Cruzeiro-MG" tipo="visitante" /></jogo><jogo horario="2018-11-19T20:00:00"><equipe gols="0" time="Fluminense-RJ" tipo="mandante" /><equipe gols="0" time="Ceará-CE" tipo="visitante" /></jogo></rodada><rodada n="34"><jogo horario="2018-11-14T19:30:00"><equipe gols="1" time="Vasco da Gama-RJ" tipo="mandante" /><equipe gols="1" time="Atlético-PR" tipo="visitante" /></jogo><jogo horario="2018-11-14T21:00:00"><equipe gols="0" time="Paraná-PR" tipo="mandante" /><equipe gols="1" time="Atlético-MG" tipo="visitante" /></jogo><jogo horario="2018-11-14T21:00:00"><equipe gols="2" time="Bahia-BA" tipo="mandante" /><equipe gols="1" time="Ceará-CE" tipo="visitante" /></jogo><jogo horario="2018-11-14T21:45:00"><equipe gols="3" time="Palmeiras-SP" tipo="mandante" /><equipe gols="0" time="Fluminense-RJ" tipo="visitante" /></jogo><jogo horario="2018-11-14T21:45:00"><equipe gols="1" time="Cruzeiro-MG" tipo="mandante" /><equipe gols="0" time="Corinthians-SP" tipo="visitante" /></jogo><jogo horario="2018-11-14T21:45:00"><equipe gols="0" time="Sport-PE" tipo="mandante" /><equipe gols="0" time="Vitória-BA" tipo="visitante" /></jogo><jogo horario="2018-11-15T17:00:00"><equipe gols="0" time="Chapecoense-SC" tipo="mandante" /><equipe gols="1" time="Botafogo-RJ" tipo="visitante" /></jogo><jogo horario="2018-11-15T17:00:00"><equipe gols="1" time="Flamengo-RJ" tipo="mandante" /><equipe gols="0" time="Santos-SP" tipo="visitante" /></jogo><jogo horario="2018-11-15T19:00:00"><equipe gols="1" time="São Paulo-SP" tipo="mandante" /><equipe gols="1" time="Grêmio-RS" tipo="visitante" /></jogo><jogo horario="2018-11-15T21:00:00"><equipe gols="2" time="Internacional-RS" tipo="mandante" /><equipe gols="0" time="América-MG" tipo="visitante" /></jogo></rodada><rodada n="33"><jogo horario="2018-11-10T17:00:00"><equipe gols="0" time="América-MG" tipo="mandante" /><equipe gols="1" time="Paraná-PR" tipo="visitante" /></jogo><jogo horario="2018-11-10T17:00:00"><equipe gols="1" time="Corinthians-SP" tipo="mandante" /><equipe gols="1" time="São Paulo-SP" tipo="visitante" /></jogo><jogo horario="2018-11-10T19:00:00"><equipe gols="2" time="Botafogo-RJ" tipo="mandante" /><equipe gols="1" time="Flamengo-RJ" tipo="visitante" /></jogo><jogo horario="2018-11-10T19:00:00"><equipe gols="2" time="Atlético-PR" tipo="mandante" /><equipe gols="0" time="Cruzeiro-MG" tipo="visitante" /></jogo><jogo horario="2018-11-11T17:00:00"><equipe gols="1" time="Atlético-MG" tipo="mandante" /><equipe gols="1" time="Palmeiras-SP" tipo="visitante" /></jogo><jogo horario="2018-11-11T17:00:00"><equipe gols="2" time="Grêmio-RS" tipo="mandante" /><equipe gols="1" time="Vasco da Gama-RJ" tipo="visitante" /></jogo><jogo horario="2018-11-11T17:00:00"><equipe gols="1" time="Ceará-CE" tipo="mandante" /><equipe gols="1" time="Internacional-RS" tipo="visitante" /></jogo><jogo horario="2018-11-11T17:00:00"><equipe gols="2" time="Vitória-BA" tipo="mandante" /><equipe gols="2" time="Bahia-BA" tipo="visitante" /></jogo><jogo horario="2018-11-11T19:00:00"><equipe gols="0" time="Fluminense-RJ" tipo="mandante" /><equipe gols="0" time="Sport-PE" tipo="visitante" /></jogo><jogo horario="2018-11-12T20:00:00"><equipe gols="0" time="Santos-SP" tipo="mandante" /><equipe gols="1" time="Chapecoense-SC" tipo="visitante" /></jogo></rodada><rodada n="32"><jogo horario="2018-11-03T17:00:00"><equipe gols="0" time="Atlético-MG" tipo="mandante" /><equipe gols="1" time="Grêmio-RS" tipo="visitante" /></jogo><jogo horario="2018-11-03T17:00:00"><equipe gols="0" time="Fluminense-RJ" tipo="mandante" /><equipe gols="1" time="Vasco da Gama-RJ" tipo="visitante" /></jogo><jogo horario="2018-11-03T19:00:00"><equipe gols="3" time="Palmeiras-SP" tipo="mandante" /><equipe gols="2" time="Santos-SP" tipo="visitante" /></jogo><jogo horario="2018-11-04T17:00:00"><equipe gols="1" time="Paraná-PR" tipo="mandante" /><equipe gols="1" time="Vitória-BA"
